### ISSUE TITLE
Fill Byte is not bounded to [0,256) and causes OverflowError when writing to file.

### ISSUE THREAD

**Issue by zachsez** [poodle-dog/bingen#1]
Commit: a5408bcbcdf20d55626f65c489f5cdf43830b313
Recreate:
`python3 bingen/bingen.py 0xf9 0x100 -c 16 --filename out.txt`

Suggested fix add `chunkval &= 0xff` on line 43:
```python
for a in range(args.length // args.chunk):
    list_data += generate_chunk(chunkval,args.chunk)
    chunkval += 1
    chunkval &= 0xff
```

**Comment by poodle-dog** [comment]
Nice catch. Proposed solution checks out. Fixed in d23c5d4
